config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :new, :create, :show] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create, :destroy]
    end
  end

  root to: 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post

  after_create do |_post|
    update_post_comments_counter
  end

  def update_post_comments_counter
    post.increment_comments_counter
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post

  after_create do |_like|
    update_post_likes_counter(true)
  end

  after_destroy do |_like|
    update_post_likes_counter(false)
  end

  def update_post_likes_counter(input)
    post.increment_likes_counter(input)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, foreign_key: 'post_id'
  has_many :likes, foreign_key: 'post_id'
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  paginates_per 3

  validates :title, :text, presence: true, length: { maximum: 250 }
  validates :comments_counter, :likes_counter, comparison: { greater_than_or_equal_to: 0 },
                                               numericality: { only_integer: true }

  after_create do |_post|
    update_user_post_counter
  end

  def increment_likes_counter(input)
    return update(likes_counter: self.likes_counter += 1) if input

    update(likes_counter: self.likes_counter -= 1)
  end

  def increment_comments_counter
    update(comments_counter: self.comments_counter += 1)
  end

  def update_user_post_counter
    author.increment_posts_counter
  end

  def most_recent_comments(limit = 5)
    comments.order(created_at: :desc).limit(limit)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  # Associations
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  # Validations
  validates :name, :bio, :photo, presence: true
  validates :posts_counter, comparison: { greater_than_or_equal_to: 0 }, numericality: { only_integer: true }

  # Returns the user's most recent posts, sorted by creation date, and limited to a given number (defaulting to 3)
  def recent_posts(limit = 3)
    posts.order(created_at: :desc).limit(limit)
  end

  # Increments the user's `posts_counter` attribute by one
  def increment_posts_counter
    update(posts_counter: self.posts_counter += 1)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :bio, :photo, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :bio, :photo, :email, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  layout 'standard'

  def new
    @comment = Comment.new
  end

  def create
    post = Post.find_by(id: params[:post_id])

    @comment = Comment.new(author: current_user, post:, text: comment_params)

    if @comment.save
      flash[:success] = 'Comment saved successfully'
      redirect_to user_post_path(user_id: params[:user_id], id: params[:post_id])
    else
      flash.now[:error] = "Error: couldn't save comment"
      render :new, alert: 'Error occured!'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)[:text]
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  layout 'standard'

  def create
    post = Post.find_by(id: params[:post_id])
    user = current_user
    @like = Like.new(author: user, post:)

    if @like.save
      flash[:success] = 'Likes added successfully'
      redirect_to user_post_path(user_id: params[:user_id], id: params[:post_id])
    else
      flash.now[:error] = 'Error occured'
    end
  end

  def destroy
    @like = Like.find_by(author_id: current_user.id).destroy

    flash[:success] = 'Likes removed successfully'
    redirect_to user_post_path(user_id: params[:user_id], id: params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  layout 'standard'

  def index
    @user = User.find_by(id: params[:user_id])
    @posts = if @user.present?
               @user.posts.page params[:page]
             else
               []
             end
  end

  def show
    @comment = Comment.new
    @current_user = current_user
    @post = Post.includes(:comments).find(params[:id])
  rescue ActiveRecord::RecordNotFound
    @post = 'There are no posts'
  end

  def new
    @post = Post.new
  end

  def create
    user = User.find_by(id: params[:user_id])
    @post = Post.new(author: user, title: post_params[:title], text: post_params[:text])
    if @post.save
      flash[:success] = 'Post saved successfully'
      redirect_to user_posts_path
    else
      flash[:success] = "Invalid input, post wasn't saved"
      redirect_to new_user_post_path(user_id: params[:user_id])
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    @user = User.includes(:posts, :comments).find_by(id: params[:id]) || 'There is no user'
    @posts = @user.posts.limit(3).page(params[:page])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'User saved successfully'
      redirect_to users_path
    else
      flash.now[:error] = "Error: couldn't save user"
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :bio, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<h2>Create a new comment</h2>

<%= form_with model: @comment, url: user_post_comments_path do |form| %>
  <li class="comment_form"><%= form.label :"text:" %>
  <%= form.text_area :text, :required=>true %>
  </li>
    <%= form.submit "Add comment" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>  
  <%= button_to "Logout", destroy_user_session_path, method: :delete, id: "destroy-session" %>
  <%= yield %>
   <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>
  </body>
</html>

app/views/layouts/standard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "style" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>
  <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<% if @posts.empty? %>
  <%= render partial: 'shared/user', locals: { user: @user } %>
  <p><%= "There is no post to display" %></p>
<% else %>
  <%= render partial: 'shared/user', locals: { user: @user } %>
  <% @posts.each do |post| %>
    <% @user.posts.each_with_index do |post, index| %>
    <%= render partial: 'shared/post', locals: { post: post, index: index + 1 } %>
  <% end %>
<% @posts.each do |post| %>
  <%= render partial: 'shared/comment', collection: post.comments, as: :comment %>
<% end %>
  <% end %>
<% end %>

<%= paginate @posts %>

app/views/posts/new.html.erb
<h2>Create a new post</h2>

<%= form_with model: @post, url: user_posts_path(user_id: params[:user_id]), html: { class: "form" } do |form| %>
  <li id="input_title"><%= form.label :"title:" %>
  <%= form.text_field :title, :required=>true %>
  </li>
  <li><%= form.label :"text:" %>
  <%= form.text_area :text, :required=>true %>
  </li>
    <%= form.submit "Add post" %>
<% end %>

app/views/posts/show.html.erb
<% if !@post.kind_of? String %>
     <div class="detailed_post">
        <div id="post-container">
            <div class="post-top-section">
                <h4>Post #1 by <%= @post.author.name %></h4>
                <p id="comments-likes">Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %></p>
            </div>
            <p><%= @post.text %></p>
        </div>
        <div>
            <% @post.comments.each do |comment| %>
                <%= render partial: "shared/comment", locals: { comment: comment } %>
            <% end %>
        </div>
        <div class="comment_like_holder">
            <button id="add_comment"><%= link_to 'Add comment', new_user_post_comment_path(user_id: @post.author.id, post_id: @post.id) %></button>
            <%= form_with url: user_post_likes_path(user_id: @post.author.id, post_id: @post.id), scope: :data do |form| %>
                <%= form.submit "Like" %>
            <% end %>
        </div>
    </div>
<% else %>
    <p><%= @post %></p>
<% end %>

app/views/shared/_comment.html.erb
<div class="single_comment">
  <div class="comment_user_profile">
    <img id="comment_user_photo" src= <%= comment.author.photo %> alt="user_image" />
    <p><%= comment.author.name %></p>
    </div>
    <div class="comment_text_holder">
        <p><%= comment.text %></p>
        <p id="created_at"><%= comment.created_at %></p>
    </div>
</div>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
<button id="login_btn">
  <%= link_to "Log in", new_session_path(resource_name) %>
  </button>
  <br />
<% end %>
<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
<button id="sign_in_btn">
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
  </button>
<% end %>
<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>
<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>
<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>
<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/shared/_post.html.erb
<a href="<%= user_post_path(post.author.id, post.id) %>" id="post_link" class="box">
  <h4>Post #<%= index %></h4>
  <p><%= post.text.first(150) %></p>
  <p id="comments-likes">Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></p>
</a>

app/views/shared/_user.html.erb
<div id="user">
  <% if user.present? %>
    <img id="user-img" src= <%= user.photo %> alt="user_image"/>
    <h2><%= user.name %></h2>
    <p id="post-count">Number of posts: <%= user.posts_counter %></p>
  <% else %>
    <p>User not found</p>
  <% end %>
</div>

app/views/users/index.html.erb
<% if @users.empty? %>
    <p><%= "There are no users to display" %></p>
<% else %>
    <h3>List of all users</h3>
    <% @users.each do |user| %>
        <a href= <%= user_path(id: user.id) %> class="single_user">
        <%= render partial: "shared/user", locals: { user: user } %>
        </a>
      <% end %>
<% end %>

app/views/users/new.html.erb
<h2>Create a new user</h2>

<%= form_with model: @user, html: { class: "form" }  do |form| %>
  <li><%= form.label :"name:" %>
  <%= form.text_field :name, :required=>true %>
  </li>
  <li id="input_bio"><%= form.label :"bio:" %>
  <%= form.text_area :bio, :required=>true %>
  </li>
  <li><%= form.label :"photo(url):" %>
  <%= form.text_field :photo, :required=>true %>
  </li>
    <%= form.submit "Register" %>
<% end %>

app/views/users/show.html.erb
<% if !@user.kind_of? String %>
        <%= render partial: 'shared/user', locals: { user: @user } %>
    <div class="box">
        <p>Bio</p> <br>
        <%= @user.bio %>
    </div>
    <% @user.posts.each_with_index do |post, index| %>
    <%= render partial: 'shared/post', locals: { post: post, index: index + 1 } %>
  <% end %>
  <div class="buttons_holder">
        <button id="create_post"><%= link_to 'Create post', new_user_post_path(user_id: @user.id) %></button>
        <% if !@user.posts.empty? %>
            <button id="show_all_posts"><%= link_to 'Show all posts', user_posts_path(user_id: @user.id) %></button>
        <% end %>
    </div> 
<% else %>
    <p><%= @user %>
<% end %>

<%= paginate @posts, per_page: 3 %>